# Dockerfile.player
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      net-tools iproute2 iputils-ping iputils-arping netcat-openbsd tcpdump nmap dnsutils procps curl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /home/player

COPY init_player.sh /usr/local/bin/init_player.sh
RUN chmod +x /usr/local/bin/init_player.sh

ENTRYPOINT ["/usr/local/bin/init_player.sh"]
CMD ["/bin/bash"]


