# docker-compose.yml
networks:
  ctfnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24

services:
  flagserver:
    build:
      context: .
      dockerfile: Dockerfile.victim
    networks:
      ctfnet:
        ipv4_address: 172.28.0.2
    mac_address: 02:42:ac:11:00:02
    restart: unless-stopped

  player:
    build:
      context: .
      dockerfile: Dockerfile.player
    networks:
      ctfnet:
        ipv4_address: 172.28.0.42
    tty: true
    stdin_open: true
    privileged: true

